const w : number = window.innerWidth
const h : number = window.innerHeight
const parts : number = 4
const scGap : number = 0.02 / parts
const strokeFactor : number = 90
const sizeFactor : number = 2.9
const backColor : string = "#bdbdbd"
const colors : Array<string> = ["#2196F3", "#4CAF50", "#F44336", "#3F51B5", "#FF9800"]
const delay : number = 90
